discord_token = "Discord Bot Token"
host = "0.0.0.0:8080"
homeserver_url = "https://matrix.example.com:443"
server_name = "example.com"

[[room]]
discord = "Room ID"
discord_guild = "Guild ID"
matrix = "Room ID"
webhook = "Discord Webhook"
